error: used parameter type in error cause instead of function
V6eval change to use MmParameter instead of MmData in some
error cause's define, so this patch fix to used it.

Signed-off-by: Wei Yongjun <yjwei@cn.fujitsu.com>